apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t58ui78sg-python
  janus-idp.io/tekton: t58ui78sg-python
  backstage.io/kubernetes-id: t58ui78sg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t58ui78sg-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
